options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/gmail-ai-assistant
      - .

# Push the image (Cloud Run will pull it automatically)
images:
  - gcr.io/$PROJECT_ID/gmail-ai-assistant
